# Generated by Django 4.1.4 on 2022-12-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoplist',
            fields=[
                ('contract_id', models.IntegerField(primary_key=True, serialize=False)),
                ('contract_desc', models.CharField(max_length=400)),
                ('contract_type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'contracts',
            },
        ),
    ]
